#!/bin/bash

#PBS -lwalltime=48:00:00
#PBS -lselect=1:ncpus=1:mem=32gb:ngpus=1

set -e

cd $PBS_O_WORKDIR

eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate pytorch_env

python -m src.scripts.runner --wandb

conda deactivate