name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make test
      run: make test
      
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make test
      run: make test

  # build-windows:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: make
  #     run: make
  #   - name: make test
  #     run: make test
